services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - ./app:/app/app
      - model_cache:/models
    restart: unless-stopped

volumes:
  model_cache: