services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - GENERATIVE_MODEL_NAME=theSOL1/kogrammar-base
      - MODEL_CACHE_DIR=./models
      - MAX_TEXT_LENGTH=1000
      - USE_GPU=false
    volumes:
      - ./app:/app/app
      - model_cache:/app/models
    restart: unless-stopped

volumes:
  model_cache: